### ISSUE TITLE
Mod loading error has occurred on server - Bug

### ISSUE THREAD

**Issue by Roonis1** [JMilamber/Brass_Amber_BattleTowers#102]
**Describe the bug**
Brass Amber BattleTowers failed to load on the server, causing it to crash on start up. 

**To Reproduce**
Things needed to reproduce the behavior:
1. Best I can do is link a zip file of my mods. https://www.mediafire.com/file/ihbi0hy5hlcnndo/Modpack_Mods.zip/file 
2. 1.18.2 Minecraft version, Forge 1.18.2-40.1.84
3. BrassAmber Battle Towers v2.3.0
4. Yes using Scaling Health Mod's Datapack, A datapack to remove Elytras in item frames entity, Anti Enderman Grief from Vanilla Tweaks.
5. Server 
6. OS: Windows

**Expected behavior**
The mod to load up perfectly fine

Crash report:

[crash-2022-11-03_06.37.16-fml.txt](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/files/9968431/crash-2022-11-03_06.37.16-fml.txt)

**Comment by DTX3** [comment]
Getting the same with our server using 1.18.2-2.3.0

[minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
Brass-Amber BattleTowers (ba_bt) has failed to load correctly

[crash-2022-11-09_10.57.01-fml.txt](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/files/9970184/crash-2022-11-09_10.57.01-fml.txt)

**Comment by JMilamber** [comment]
@Roonis1 The crash report you linked is from September third and does not mention Battle-towers. Possibly grabbed wrong file? 

Ah yes, I can see the problem in @DTX3's crash report. 

My apologies, I have a reference to the single-player server that is not skipped when on a dedicated server. 
Will attempt to fix tonight, should be a new version up by tomorrow.

**Comment by JMilamber** [comment]
@Roonis1 @DTX3 fixed in re-uploaded 2.3.0 jar on CF :)
