### ISSUE TITLE
Game Crashed whilst ticking entity (Land/Ocean Obelisk) - World is now corrupted

### ISSUE THREAD

**Issue by Mqony** [JMilamber/Brass_Amber_BattleTowers#108]
**Describe the bug**
After exploring the world for a little, I found an Ocean Battle Tower. I went through it normally, however, after a minute or so, the game randomly froze and crashed. The world is corrupted and no longer works.

**To Reproduce**
Things needed to reproduce the behavior:
1. In Crash Report
2. Minecraft 1.18.2 - Forge 40.2.0
3. v2.3.1
4. No datapacks/self-created loot tables
5. Singleplayer
6. OS: Windows 10

**Expected behavior**
Game not to crash.

**Screenshots**
N/A

**Additional context**
This crash happens with both Ocean and Land Towers. When encountering a Battle Tower, everything will work fine for around a minute. After that, the game will randomly freeze and crash. The world is now corrupted and will crash the game instantly on world startup.

[crash-2023-01-05_10.10.21-server.txt](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/files/10355061/crash-2023-01-05_10.10.21-server.txt)

**Comment by JMilamber** [comment]
Potentially a forge 40.2.0 related bug, as BattleTowers is not using 40.2.0 yet- investigating today. 
Did you add remove items from the item pools in the BT config?

**Comment by Camawama** [comment]
the same thing is happening on my server but there is one thing that is different from your issue. It only happens whenever a floor is cleared on one of the battle towers. It appears to be related to the loot in the chests but it could also be the fact that I'm using a server running **MAGMA**

**Comment by JMilamber** [comment]
@Camawama I Dont know if it was also you, but someone reported the same problem you described in the discord.
MAGMA uses bukkit APIs, and there is a function that we use to fill the chests with loot that bukkit changes via mixins. 
Unfortunate, but I can't fix that on my end.

**Comment by JMilamber** [comment]
Closing due to no response from the issue creator.

**Comment by Shybella** [comment]
Crash: https://pastebin.com/Je2MzjCX
