### ISSUE TITLE
Glitch effect with tree foliage

### ISSUE THREAD

**Issue by uricus** [JMilamber/Brass_Amber_BattleTowers#109]
Battle Towers v1.6.3 for 1.16.5. Combined with Optifine, it creates a terrible glitch effect with tree foliage when I am far.

Edited 01.30.2023: The problem still exist even without optifine (foliage work normally, but plants no)

1. OptiFine HD U G8
   BrassAmber BattleTowers
2. 1.16.5 & Forge - 36.2.34
3. v1.6.3
4. No datapack
5. No config changes
6. Singleplayer
7. Windows

There is no screenshot, as the problem needs to be seen live.

May think that this is nonsense. I was also surprised too, because the structural mod can't do this. Impossible to describe it in words. You can install these mods and compare Optifine with BABT and without it (in graphics settings you should have Leaves - Fansy). I am sure that the problem is in the Battle Towers, everything works fine with other mods. I will be very grateful if you fix it. Thank you.

**Comment by JMilamber** [comment]
Are you using the Excalibur texture pack for 1.16.5?
If so I believe the texture pack has had some problems with optifine and leaf models.
I can't remember if they found a fix. Any shaderpacks as well?

**Comment by Uricus** [comment]
No texturepacks, no shaderpacks, all default settings

**Comment by uricus** [comment]
No texturepacks, no shaderpacks. All default settings. I think to understand the problem you need to check it yourself (optifine with babt, without it, with different mods)

**Comment by Uricus** [comment]
I recorded a video to help you understand the problem.
https://youtu.be/F8qy9py2Y3s

**Comment by Uricus** [comment]
I recorded a video to help you understand it. You can see that the problem appears not only with foliage, but also a little with snow.
https://youtu.be/F8qy9py2Y3s

**Comment by uricus** [comment]
I recorded a video to help you understand it. You can see that the problem appears not only with foliage, but also a little with snow, etc.
https://youtu.be/F8qy9py2Y3s

**Comment by uricus** [comment]
I also checked Battle Towers without Optifine. Everything is fine with the foliage, but there is a similar bug with plants (grass, vines, harvest, etc).

**Comment by JMilamber** [comment]
Thank you for the video that was very helpful! That is absolutely wild.  I've never seen that before.

My only current guess is maybe the forge version diff - BT for 1.16.5 was done for forge 36.2.0
Possible some changes in the newer 36.2.34 are causing this...? Idk

Any chance you could try with 36.2.0 and see if it happens then too?
Apologies I don't really have the time at the moment to manually go testing for this.

**Comment by Uricus** [comment]
No problem. I don't now about what v1.6.5 u said, but i think you mean 1.6.3 (last version for 1.16.5).
I checked it on forge 36.2.0 and problem still exist.

**Comment by Uricus** [comment]
No problem. I don't now about what v1.6.5 u said, but i think you mean 1.6.3 (last version for 1.16.5).
I checked it on forge 36.2.0 and problem still exist.

**Comment by Uricus** [comment]
No problem. I don't now about what v1.6.5 u said, but i think you mean 1.6.3 (last version for 1.16.5).
I checked it on forge 36.2.0 and problem still exist.

**Comment by uricus** [comment]
No problem. I don't know about what v1.6.5 u said, but i think you mean 1.6.3 (last version for 1.16.5).
I checked it on forge 36.2.0 and problem still exist.

**Comment by JMilamber** [comment]
Very odd, I really have no idea what could cause this then. My first instinct would be a mixin, but BrassAmberBattleTowers does not use any mixins.... 
Maybe it's Optifine related?

**Comment by JMilamber** [comment]
Just checked the Optifine page, and there is no download that is compatible with forge 36.2.0 unfortunately. I guess that is where the problem is. The highest version of Forge that Optifine for 1.16.5 supports is supposedly Forge 36.1.0

**Comment by uricus** [comment]
JMilamber, I wrote many times that the problem remains even without Optifine, but already problems with plants.
