### ISSUE TITLE
Generation

### ISSUE THREAD

**Issue by Willem07** [JMilamber/Brass_Amber_BattleTowers#113]
Please tell me why the search for the structure takes a very long time?
[latest.log](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/files/10950706/latest.log)

forge: 1.18.2-40.2.0
mod version: 2.3.5
[mods list.txt](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/files/10950825/mods.list.txt)

And also tell me why there is no boss and green wool instead of spawners
![2023-03-12_15 29 43](https://user-images.githubusercontent.com/51959206/224545437-eb5042f2-eb65-49b7-9dc6-cf5e8367229e.png)

**Comment by JMilamber** [comment]
/locate does not work well with BattleTowers, they have extra checks in their spawning that allows them to be placed in the chunks surrounding the check (less checks = less lags)
Unfortunately this breaks the /locate command as it only checks the center chunk. 
Unfortunately as well, the /locate command only stops at like 1 million blocks away from the players, and the farther out it checks the laggier it gets.
Every once in a while the spawn check for  a battletowers will spawn one in the chunk that the minecraft also check with/locate and will finally return.

As for the reason the spawners are not there, the green wool you see is replaced when the tower is loaded in by the "Obelisk" entity that is spawned in at the bottom of the tower. It seems that some mod in your modlist ahs made either that entity or the monolith entity at the top of the tower get removed which would prevent any of the spawners from being created. 

Unfortunately I do not know which mod it is, If you do want to figure out which mod, you can:
1. Split your mod list in half and remove one half of your mods (excluding BattleTowers). 
2. Launch the game 
3. if the problem persists then go back to step 1
4. if it doesn't, swap to the other half of the mod list in and and return to step 2

Do this until you get down to the one mod that is the problem.

The other possible reason for this is:
If this is on a server or a part of a modpack: the server/modpack owner has made changes to the .nbt file of the structure piece  at the top of the tower which spawns the monolith. 
If on singleplayer, you have made changes to the .nbt file of the structure piece.

Best of luck

**Comment by Willem07** [comment]
Thank you for the information! As for the green wool, I only occasionally found such towers, all the others were fine. Of course, I can try to find out the conflicting mod and I will immediately write here.

**Comment by Willem07** [comment]
Unfortunately, I could no longer find the broken towers to check the problem in the logs.
