### ISSUE TITLE
When New Ocean Tower Generate Cause A Lot Of Lag In A Single Player World Open To Lan

### ISSUE THREAD

**Issue by ColaLiao** [JMilamber/Brass_Amber_BattleTowers#116]
**Describe the bug**
When New Ocean Tower Generate Cause A Lot Of Lag In A Single Player World Open To Lan

**To Reproduce**
Things needed to reproduce the behavior: (Replace with your answer)
1. [Your Mod List](https://drive.google.com/file/d/1SdJc-1p4YMsVgg0vsS5j0Isa6j_Ch3ob/view?usp=sharing)
2. 1.18.2-40.2.0
3. The version of the mod you are using : 2.3.5
4. Any datapacks/self-created loot-tables? No
5. Any config changes? No
6. Server or Singleplayer? Singleplayer but open to lan
7. OS: [e.g.Widnows/Mac/Linux] : Widnows

**Expected behavior**
When New Ocean Tower Generate
mobs stop moving
block can not break
chests, boxes, backpacks can not open
player will disconnected except owner

need to wait minutes after these happened.

**Comment by ColaLiao** [comment]
[0421.txt](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/files/11289938/0421.txt)

**Comment by JMilamber** [comment]
There is now an option for a half sized trench in the config as of v2.3.8
