### ISSUE TITLE
Crash when golem is hit by arrow fired from crossbow with piercing enchantment

### ISSUE THREAD

**Issue by MaxWasUnavailable** [JMilamber/Brass_Amber_BattleTowers#117]
**Describe the bug**
Crash when golem is attacked by crossbow with piercing enchantment.

**To Reproduce**
Things needed to reproduce the behavior: (Replace with your answer)
1. https://pastebin.com/taMLy5GJ
2. 1.18.2 - Forge 40.2.1
3. 1.18.2-2.3.5
4. Yes, Geolosys datapacks. Nothing related to mobs, entities, or vanilla.
5. Only changes in separation & generation distance
6. Both SP & MP.
7. OS: Windows & Linux

**Expected behavior**
No crash.

**Screenshots**
Not applicable.

**Additional context**
Not applicable.

**Comment by JMilamber** [comment]
Pastbin line 408 
"Domestication Innovation (by sbom_xela)"

Domestic innovation is a mod that directly conflicts with the Golems for some currently unknown reason, making it impossible to damage them unless you are crouching. Most likely this is doing something weird when the piercing enchantment does its damage.

**Comment by JMilamber** [comment]
@MaxWasUnavailable  see this issue. https://github.com/AlexModGuy/DomesticationInnovation/issues/52
seemingly already reported on their page.
