### ISSUE TITLE
(Ocean Monolith) - Bug

### ISSUE THREAD

**Issue by KorpSelene** [JMilamber/Brass_Amber_BattleTowers#118]
**Describe the bug**
Keys dont work on summoning the golem once the tower was cleared. Cant replace the monolith in creative. Unable to do the dungeon and retrieve loot because of this. New keys also didnt work.

**Comment by JMilamber** [comment]
Ocean Monolith requires 2 Keys, followed by the Eye of the Land Golem to activate. (Dropped when killing the Land Golem) 
Monolith changes textures after 2 keys to indicate this
