### ISSUE TITLE
Completed Ocean Monolith Removing Placed Blocks Under It - Bug

### ISSUE THREAD

**Issue by cranberriez** [JMilamber/Brass_Amber_BattleTowers#119]
**Describe the bug**
After completing the ocean monolith it all falls and creates a large pit down to the void as expected. It gets filled in with water eventually. Placing any block that is not naturally a part of the tower (Oak planks, dirt, and granite were what I tested with) and then reloading the chunks causes those new blocks to be removed. Blocks were placed around 10-20 blocks under the top section of the tower that remained and went outward to the very edge of the hole created by the tower. All of these blocks were removed up leaving and coming back to the chunks (refer to video). 

**To Reproduce**
Things needed to reproduce the behavior:
1. Just BrassAmber BattleTowers && Dawncraft Modpack (Occurs on Both)
2. Minecraft 1.18.2, Forge 40.2.2
3. BrassAmberBattleTowers-1.18.2-2.3.5.jar
4. Any datapacks/self-created loot-tables? No
5. Any config changes? No
6. Server or Singleplayer? Multiplayer Server
7. OS: Windows 10 & Windows 11

**Expected behavior**
I expected to be able to place blocks and not have them removed. The tower was properly destroyed, the void hole was filled in with water fairly quickly.

**Screenshots**
[Provided video ](https://discord.com/channels/780076404519600148/961515067059372063/1104449225506435193) on the official discord server. 

**Additional context**
Tested in a multiplayer server with 8Gb of memory on 2 different machines.
1 player online in both situations.
Tested with just this mod installed, and in the Dawncraft modpack.
Destroys blocks all the way down until Y -29 & to 61 blocks away from center

Server Arguments: -Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true

**Comment by JMilamber** [comment]
Confirmed in a test world. Now to bugfix.....

**Comment by JMilamber** [comment]
Found the problem will be fixed in the next 1.18.2 update (bugfixes)
Soon _tm_

**Comment by JMilamber** [comment]
@cranberriez Fixed in the most recent beta, needs some testing to ensure I haven't added any bugs but the update should be out soon. 
Unfortunately, I don't know how quickly Dawncraft will update to that version.

**Comment by JMilamber** [comment]
Fixed in version 2.3.8 of BT
