### ISSUE TITLE
No matter what I do it will not allow me to open bahryn'muul's chest

### ISSUE THREAD

**Issue by Arsonation** [JMilamber/Brass_Amber_BattleTowers#123]
No matter what I do I will clear every spawner all the way up to the top and kill the golem but it will not let me open his chest. 

I'm playing on 1.18.2 and forge 40.2.4 

no modifications to the loot tables 

I haven't changed the configs in any way.

BrassAmberBattleTowers-1.18.2-2.3.8.jar

singleplayer 

Windows 10

Mods:

Alex's Mobs

Apotheosis

AppleSkin

Architectury API

Ars Nouveau

AutoRegLib

Balm

Bookshelf

Borderless Window

BrassAmber BattleTowers

Callable Horses

Carry On

Chunk Loaders

Citadel

Cloth Config API

Comforts

Configurable Cane

Construction Wand

Controlling

Crafting Tweaks

CraftTweaker

Create

CreativeCore

Curios API

Enchantment Descriptions

Enhanced Mob Spawners

Entity Culling Fabric/Forge

Farmer's Delight

Feature NBT Deadlock Be Gone

Flywheel

FTB Library

FTB Ultimine

HT's TreeChop

Inspirations

Integrated API

Integrated Dungeons and Structures

Iron Chests

ItemPhysic Full

Jade 🔍

JEITweaker

JourneyMap

Just Enough Items (JEI)

Konkrete

Library Ferret

Magnesium/Rubidium Dynamic Lights

Magnesium/Rubidium Extras

Majrusz Library

Majrusz's Progressive Difficulty

Mantle

Max Health Fix

Moonlight Lib

More Villagers

Mouse Tweaks

Not Enough Crashes

Nyf's Quivers

Paladin's Furniture

Paragliders

Passable Foliage 🌳

Patchouli

Placebo

Quark

Rubidium
Simple Storage Network

Sophisticated Backpacks

Sophisticated Core

StackablePotions

Storage Drawers

SuperMartijn642's Config Lib

SuperMartijn642's Core Lib

Supplementaries

Tinkers Construct

Waystones

XP Tome

Edit: Sorry I didn't see the spot that required the mod list :/

**Comment by JMilamber** [comment]
Please either use the bug report template for your issue, or look at the template and edit this issue with the needed information.
