### ISSUE TITLE
White Wool is preventing Spawner generation due to Pride Month

### ISSUE THREAD

**Issue by onethirdparty** [JMilamber/Brass_Amber_BattleTowers#125]
I'm using DawnCraft; with your version saying it is 2.3.5. But I think this applies to all versions regardless.

During pride month, Mojang randomises the generation of wool to be different colours. And apparently this mod uses white wool as a placeholder for generating the spawners. An obvious fix would be to simply change your computer's internal clock backwards or forwards, but I am purchasing a server where that it is not exactly possible.

I hope this is clear; even if it doesn't fully go along with the guidelines of these issue reports.

**Comment by JMilamber** [comment]
Using the Bug issue template next time would be appreciated.

Thank you for notifying my me of this, did not know that Mojang had down that for pride month, there definitely is potential for that to be messing with the tower. 

We do use Green and Blue wool for the Land Towers and Ocean Towers respectively as spawner placeholders. 

I will look into using something else instead of wool. 
Look for a fix in the next few days.

**Comment by onethirdparty** [comment]
@JMilamber Word; thank you for the fix. Love your mod

**Comment by JMilamber** [comment]
Apologies but I can't seem to find any information on this can you post a link to where you heard about this? 

> During pride month, Mojang randomises the generation of wool to be different colours. 

Are you sure it is not a mod included in Dawncraft? they have messed with our mod quite a bit for unknown reasons.

**Comment by onethirdparty** [comment]
@JMilamber I did my own testing for this matter because I heard it on the Dawncraft discord server. I know that it cannot be any modification done by the Dawncraft development team because I have an older version of the modpack which was working as intended during May. I do not know why Mojang doesn't officially disclose that they've made this change; but they have.

I have also added no mods that would have changed this behaviour in anyway.

**Comment by onethirdparty** [comment]
@JMilamber I would also like to say that I find your texture design for the floating magical thing at the bottom of the tower to be quite beautiful. I wish there was a way we could pick it up and place it as decoration after beating the golem at the top.

**Comment by JMilamber** [comment]
@onethirdparty Should be fixed in v2.3.10 on CurseForge.

There are plans in the future for allowing the player to create their "own" Towers via end-game content. :)

**Comment by onethirdparty** [comment]
@JMilamber Thank you so much for the speedy fix to the problem! I noticed on your Discord that you guys were quite mift about all the Dawncraft players coming on and asking about the problem.


I'm sorry if we were a bother and I'm grateful for your patience. Love your mod; continue to do your great stuff boss.

**Comment by JMilamber** [comment]
@onethirdparty Yeah, all good. I don't have a problem with the Players themselves, or really the Devs either tbh. Just kind of confused that the Pack Devs never reached out when (at least from our perspective) there were so many people reporting problem lol. 

To be fair I'm sure the Pack Dev/Devs are fairly busy themselves.

I really appreciate you coming to the GitHub and making a report. (Its a lot easier to track on here than through a discord channel lol)
