### ISSUE TITLE
Ocean towers have multiple problems - Bug

### ISSUE THREAD

**Issue by Traehgniw** [JMilamber/Brass_Amber_BattleTowers#128]
**Describe the bug**
Problem one: the spawners are often not there even after defeating a land battletower so you can just immediately open the chests. The chests then do not have keys and you must spawn the keys in.

Problem two: When they generate they generate first and then carve their giant pit, uprooting any kelp and causing a massive lagspike.

Problem three: The boss moves at an absurd speed making it nearly impossible to hit. It is so fast it is all but teleporting and a friend compared it to something from Dragon Ball.

Problem four, probably the worst: When you DO complete it and it falls apart, it breaks the bedrock and deletes the water, making a void hole. Multiple people on the server fell into the void hole and had to /home teleport out before they died to the void.

**To Reproduce**
Things needed to reproduce the behavior: (Replace with your answer)
1. Your Mod List the You Like Food modpack on Curseforge: https://www.curseforge.com/minecraft/modpacks/you-like-food
2. Your Minecraft Version & Forge version 1.18.2 Minecraft, 40.2.4 Forge
3. The version of the mod you are using 2.3.8
4. Any datapacks/self-created loot-tables? Vanilla Tweaks.
5. Any config changes? No
6. Server or Singleplayer? Problems one and two confirmed to happen on both singleplayer and server. Did not attempt to fight boss on singleplayer, only on multiplayer.
7. OS: [e.g.Widnows/Mac/Linux] Problems one and two confirmed on Windows and Ubuntu Linux. Problems three and four occurred on the server which is Ubuntu Linux. Have not confirmed on Mac.

**Expected behavior**
Problem one: I would expect the spawners to always be there if you have defeated a land battletower. 

Problem two: I would expect it to generate pit and all at once and not uproot any kelp or other, mod-added, kelplike plant to avoid massive lagspikes.

Problem three: I would expect there to at least be a method of slowing the boss down provided to make it reasonably possible to hit.

Problem four: I would expect it to not open a hole into the void.

**Screenshots**
Void hole ):
![image](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/assets/42482668/d8ce53cf-6c92-4e2d-a30c-25da27493e80)

**Additional context**

**Comment by onethirdparty** [comment]
@Traehgniw Hey, I think this is somewhat similar to my post on the matter. Modmaker is aware that the Spawners are not working properly and is working on a way to fix it.

The reason why the spawners are broke is because they use green and blue wool as placeholders for the spawners in land and ocean towers respectively. This is a problem because Mojang, during the month of June, randomizes wool generation for pride month, though they do not explicitly disclose that they make this change.

**Comment by Traehgniw** [comment]
Land tower spawners generate fine though. We raided a freshly generated land tower and died many many times because we were in unenchanted iron at best.

**Comment by JMilamber** [comment]
@Traehgniw 

A new version is out today. (v2.3.10) Give it a go when you can, should fix problem one for you.

There is a config option for a smaller ocean trench which should help with the lag spike. 
Generating the pit "all at once"  causes a larger lag spike than doing it slightly incrementally
As the ocean tower generates after the ocean floor, there is no way to generate it without uprooting ocean floor plants. 
Currently, all kelp entities should get removed upon creation of the trench but modded plants are not. Could be a possible fix in the future. 

The ocean boss is still in progress and not finished, unfortunately, I am not very good at Entities so for the time being it will not be fixed.

The hole down through the bedrock is an intended feature and will not be going anywhere for the foreseeable future. 
Sorry that you have had a lot of problems with it.

**Comment by Traehgniw** [comment]
It wasn't deleting the kelp or the modded plants, resulting in there being so many entities that on the minimap it was just a black square of lag. 

Also, why does it generate after the ocean floor and generate a bedrock hole?

**Comment by JMilamber** [comment]
Huh it should be removing kelp entities nearby it, I'll have to look into that~

The generation is a Minecraft sided thing, that's just how all structures are done-they are a separate step from regular world generation. 

As for the bedrock hole, Lore-wise the Ocean Golem is a beast from the "void" which can be loosely interpreted as both the empty area below bedrock and as the End. 

So when the Ocean Golem is "defeated" he return to the void, dragging the tower down along with him.
