### ISSUE TITLE
[Feature Request]  Reducing the spawn rate of Towers (Mainly Ocean ones)

### ISSUE THREAD

**Issue by Reshy** [JMilamber/Brass_Amber_BattleTowers#130]
**Describe the bug**
I've noticed a lot of battle towers will spawn in the ocean, sometimes so close that they're visible from one another with a modest render distance.  They also will destroy blocks near other structures as well in their spawning phase.  They probably need to have their minimum distance between structures  increased by a good amount.

**Screenshots**
Structures getting deleted by proximity
![2023-07-30_08 07 56](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/assets/2096384/f1a8da84-5d40-409c-9830-4e2304476d1f)

![2023-07-30_08 18 12](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/assets/2096384/3214d396-658f-4d69-8e40-1bf799a91f93)
Very High Spawn Rate of the Tower

**Comment by JMilamber** [comment]
The minimum distance between towers, as well as the average separation between them can be adjusted in the mods config file. 
Are you playing with only BattleTowers? If not, what other mods do you have installed? 
Is this single player or on a server? 

Depending on your answers to the above questions, it does seem like their initial starting minimum separation may need to be increased.

**Comment by Reshy** [comment]
It's a modpack I an developing for.  The minimum separation for the sea towers is only 16 in the config file, versus 20 for the standard tower.  Considering how much terraforming the towers do, and how they can destroy any other structures that spawn near them in a large radius I'd probably make them more rare (I'd probably also make it so they don't destroy any non-natural blocks like the Prismarine of an Ocean Monument).

**Comment by JMilamber** [comment]
If you have other mods that add ocean structures, at the moment setting up something to avoid them as well as vanilla structures is something I don't have time for. 

One other question, do you have any sea level changing or ocean biome generation changing mods in your pack? If they deepen the ocean biomes or raise the sea level it would greatly increase the Ocean Tower spawn rate. 

Adding something to avoid replacing prismarine (&variants) would definitely be possible. I'll look into it. 
Trying to finish 1.20 right now though so it may not be soon. 
For now I would suggest increasing the minimum separation in the config to 20 or 24.

**Comment by Reshy** [comment]
Thanks for getting back to me, I cranked up the separation to 24 which seems to have fixed the issue.  I also enabled the smaller trench since while it's cool, it's very unkind to other structures spawning in the vicinity.

**Comment by Darkmega18** [comment]
wait. just, from an onlooker's perspective, why on earth do they need such a wide area around them cleaned out in the first place? isn't it enough to give them maybe 5 blocks in every direction clearance of the tower then just shove the tower in it? or is this something so that the structure can physically take up and protect more space if they defend their own blocks and spawn other entities? :V cause those are some very big holes. I know atomic ones would get buried and sometimes partially have their interiors covered occasionally, but thats still pretty nutty.

**Comment by JMilamber** [comment]
@Darkmega18 While a t clock clearance would technically be enough to get in on all sides, the trench is a representation of the golems of the towers power. it could be slightly smaller for avoiding structures or reducing spawn lag, but the main reason for the wide trench is the ambiance of it. Other tower related entities will eventually be spawning around the tower as well.
