### ISSUE TITLE
Only land towers spawning

### ISSUE THREAD

**Issue by inotrom15** [JMilamber/Brass_Amber_BattleTowers#133]
**Describe the bug**
Only land towers spawn in my world, no ocean towers or other types.
![image](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/assets/100209702/776873b1-122c-4ca2-8bb0-e62273176a74)

**To Reproduce**
Things needed to reproduce the behavior: (Replace with your answer)
1. Your Mod List - img below
2. Your Minecraft Version & Forge version - 1.16.5 forge 36.2.34
3. The version of the mod you are using - 1.16.5 1.6.3
4. Any datapacks/self-created loot-tables? - no
5. Any config changes? - in dungeon mod generation only
6. Server or Singleplayer? - singleplayer
7. OS: [e.g.Widnows/Mac/Linux] - windows

**Expected behavior**
Towers normally spawning in their biomes as they should (only land towers spawn, travelled hundreds of chunks in ocean and nothing)

**Screenshots**

**Additional context**

**Comment by JMilamber** [comment]
1.16.5 is the first version of the mod, more of a Beta than a full version and only has the Land Tower.
