### ISSUE TITLE
Golem can destroy any block

### ISSUE THREAD

**Issue by GoldenTotem** [JMilamber/Brass_Amber_BattleTowers#136]
**Describe the bug**
Minecraft 1.16.5  Forge 36.2.35  Mod 1.6.3

Golems can destroy any block, even bedrock. So do the collapse of towers.

**Expected behavior**
Unbreakable blocks like bedrock, barrier must not be destroy by golems and ignored in the collapse; golems may not destroy high hardness blocks like obsidian.

**Comment by JMilamber** [comment]
Neither of these problems are a bug, as there are not any reasonable times during which a golem or collapse would encounter such blocks.
