### ISSUE TITLE
Some entities cannot be summoned in command

### ISSUE THREAD

**Issue by GoldenTotem** [JMilamber/Brass_Amber_BattleTowers#137]
**Describe the bug**
Minecraft 1.16.5 Forge 36.2.35 Mod 1.6.3

Some entities like ba_bt:ocean_golem do not appear after command /summon

**Expected behavior**
Command /summon used to show the list of all entities in a mod, so every entities should appear after /summon and can be summoned.

**Comment by JMilamber** [comment]
Yes, they are not summon-able, this is by design. Any mods can choose to do this in their own code.
The command /summon shows all summon-able entities of a mod not all entities of a mod.
