### ISSUE TITLE
Out of bounds exception when golem dies

### ISSUE THREAD

**Issue by Mussa80473** [JMilamber/Brass_Amber_BattleTowers#64]
Every time I kill the golem, the game crashes with the last thing I hear being his cry of pain and anguish

**Comment by JMilamber** [comment]
Please post a log file of the crash, a screenshot of your mod list (if more than BattleTowers), and tell me what version of the mod & Minecraft you are running.

**Comment by JMilamber** [comment]
shelved due to incomplete provided information about the bug. 
(see above comment for needed info)
