### ISSUE TITLE
Land Monolith Key - Spawning issue - 2 out of 3 keys spawn in tower

### ISSUE THREAD

**Issue by JNCHGTR** [JMilamber/Brass_Amber_BattleTowers#69]
When exploring the Land Towers I have encountered multiple towers that only seem to contain 2 out of the 3 required Land Monolith Keys.

**To Reproduce**

Things needed to reproduce the behavior:
1. Your Mod List
https://gist.github.com/JNCHGTR/3670ece31d0ddfae897e70d146aa9998

2. Your Minecraft Version & Forge version
MC: 1.16.5
Forge: 36.2.22

3. The version of the mod you are using
BrassAmberBattleTowers-1.16.5-1.6.0

4. If you are using any datapacks/self-created loot-tables etc.
N/A

5. Server or Singleplayer?
Singleplayer

6. OS: [e.g.Widnows/Mac/Linux]
Windows 10

**Expected behavior**
To be able to find 3 Land Monolith Keys on every single tower -So far it's been only like 30% of towers I've seen.

**Screenshots**
N/A

**Additional context**
I was asked if the golem chest was facing any particular way in the tower without keys. I found 2/3 keys in a tower with the chest facing NORTH, then again 2/3 keys in a tower with the chest facing WEST. Interestingly enough I found 3/3 keys in a tower with a chest facing NORTH.

**Comment by JMilamber** [comment]
Wonderful, thanks for posting this @JNCHGTR! 
Thanks for using the issue template -I'll investigate this tonight

**Comment by JMilamber** [comment]
Found the problem, Mini-Boss (8th floor) has incorrect loot table for its land_chest.

Chest has the loottable of floor 7, which only has a slight chance of spawning a key, instead of loottable 8 which always sapwn a key.

**Comment by JMilamber** [comment]
May have forgotten to fix this in most recent update :/. Mb 

I'll upload another one tonight that fixes this.

**Comment by JNCHGTR** [comment]
All good! As long as it's coming to 1.16.5 lol. I'm glad I was of some help in finding a bug :)
Thanks for the effort in fixing it!

**Comment by Aquiles089** [comment]
This bug still lives btw

**Comment by Aquiles089** [comment]
More specifically, in the desert where some sand generations may destroy chests, I got a top floor with one chest once.
