### ISSUE TITLE
[1.18.1] Server Crash when summoning Land Golem - Bug

### ISSUE THREAD

**Issue by Gbergz** [JMilamber/Brass_Amber_BattleTowers#71]
**Describe the bug**

**To Reproduce**
Things needed to reproduce the behavior:
1. Modlist: [cf modpack, scroll down, click here](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-5/files/3684757)
2. Versions: MC 1.18.1 & Forge version: 39.1.2
3. Mod version: BrassAmberBattleTowers-1.18.1-2.0.1
4. If you are using any datapacks/self-created loot-tables etc.: No.
5. Server or Singleplayer?: **Server.**
6. OS: Windows.

**Expected behavior**
That the Land golem summons without the server crashing.

**Screenshots**
None

**crash-report**
https://gist.github.com/Gbergz/fac5cc41a46b46dc7b858c4102209e00

**Comment by JMilamber** [comment]
Thanks for using the issue template! 

Found the problem, will have a fix tonight.

**Comment by Gbergz** [comment]
Sweet, can I also add that the Land chests upon beating a floor are empty? (playing on TNP Limitless 5.)

**Comment by JMilamber** [comment]
Hmm that's odd, all I can guess is that there is a mod in yo ur pack that messes with loottables or chest spawning. 

Don't have time to look through the whole list myself atm.

**Comment by Gbergz** [comment]
All I can think of is the mod Lootr.

**Comment by JMilamber** [comment]
Ah yes, that is a known conflict atm unfortunatley.
Was going to suggest that next lol

**Comment by Gbergz** [comment]
If you have a list of the loot tables(name and id), I can add them to the Lootr config Blacklist.

**Comment by JMilamber** [comment]
Path: "data\ba_bt\loot_tables\chests\land_tower\tableName.json"
tableName: (.json)
1
2
3
4
5
6
7
8
roof
barrrack_junk
library_extra
library_special 

cchest name is: land_chest and land_golem_chest

**Comment by Gbergz** [comment]
Thanks :)

**Comment by JMilamber** [comment]
new version up, also fixes the spawner break with pickaxe bug, enjoy :)

(It's under review on CurseForge) forgot that they don't approve stuff on weekends *
