### ISSUE TITLE
Game crashes when shooting a golem with a twilightforest's seeker bow.

### ISSUE THREAD

**Issue by Lemonmito** [JMilamber/Brass_Amber_BattleTowers#78]
**Describe the bug**
Game crashes when shooting a golem with a twilightforest's seeker bow.

**To Reproduce**
1. See here: https://mclo.gs/p9fPfBZ
2. Minecraft Version : 1.16.5 & Forge version : 36.2.28
3. BrassAmberBattleTowers-1.16.5-1.6.2
4. nope
5. Singleplayer
6. OS: Windows 10

**Expected behavior**
Game crashes when shooting a golem with a twilightforest's seeker bow.

**Comment by JMilamber** [comment]
Thanks for using the Issue Template! 

I think I may know what caused this:
 just one question, was the golem you killed spawned via a monolith or with the /summon command?

**Comment by Lemonmito** [comment]
> Thanks for using the Issue Template!
> 
> I think I may know what caused this: just one question, was the golem you killed spawned via a monolith or with the /summon command?

/summon command spawn, I was going to test and modify the strength of the golem.

**Comment by JMilamber** [comment]
Ah, then it is a known bug I thought I had fixed, looking into it now, ill let you know once it's fixed.

**Comment by JMilamber** [comment]
Should be fixed in the most recent update! (v1.6.3)
