### ISSUE TITLE
(BattleTower Spawner) - Bug

### ISSUE THREAD

**Issue by TheLyricalSystem** [JMilamber/Brass_Amber_BattleTowers#99]
**Describe the bug**
Last spawner does not spawn on level 6 

**To Reproduce**
Things needed to reproduce the behavior:
1. Your Mod List
Using Modpack ABOE 3 1.5.2b
2. Your Minecraft Version & Forge version
1.16.5 
3. The version of the mod you are using
BrassAmberBattleTowers-1.16.5-1.6.3.jar
4. If you are using any datapacks/self-created loot-tables etc.
N/A
5. Server or Singleplayer?
Server
6. OS: [e.g.Widnows/Mac/Linux]
Windows
**Expected behavior**
Expected last spawner to spawn on level 6, unable to progress.

**Screenshots**
I have included a video
**Additional context**

https://user-images.githubusercontent.com/77907310/183280111-97e2c940-ad8e-43df-9ea1-648b30ef87dd.mov

**Comment by TheLyricalSystem** [comment]
github's video player seems to be broken, ig you need to download to see it

**Comment by JMilamber** [comment]
Gotta be honest, right after this was first posted I looked at it and couldn't figure out why this was happening and then forgot about it. A couple of times I have come back to it and looked into it again but never found the reason for this bug. 
Sorry, you ran into this, and sorry I never responded to it. 

The video player works for me, I have never seen that happen before except with the overgrown tower variant. (which this is obviously not)

So apologies again for taking forever to look at this, but I will close it for now as a very very rare bug. if it happens again then I will look into it more.

**Comment by onkkki** [comment]
it was happened again

**Comment by TheLyricalSystem** [comment]
@JMilamber someone else has the issue... a year later

**Comment by JMilamber** [comment]
Unfortunately I am no longer bug-fixing 1.16.5 as of seven-eight months ago. 

As well as seeing that this a rare occurrence (1 per year) 

Sorry that you both have had trouble with this.
